name: pokemon_card
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.0
  dartz: ^0.10.1
  get_it: ^7.6.7
  retrofit: ^4.4.1
  auto_route: ^7.8.4
  flutter_bloc: ^8.1.4
  alice: ^0.4.1
  provider: ^6.1.2
  equatable: ^2.0.5
  cached_network_image: ^3.4.1
  google_fonts: ^6.2.1
  permission_handler: ^11.3.1
  shimmer: ^3.0.0
  flutter_native_splash: ^2.3.13
  rxdart: ^0.27.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  retrofit_generator: ^8.2.1
  build_runner: ^2.4.11
  auto_route_generator: ^7.3.2

flutter:
  uses-material-design: true

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/splash_logo.png
  color_dark: "#121212"
  image_dark: assets/images/splash_logo.png

  android_12:
    image: assets/images/splash_logo.png
    icon_background_color: "#ffffff"
    image_dark: assets/images/splash_logo.png
    icon_background_color_dark: "#121212"

  web: false