name: pokemon_card
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.0
  dartz: ^0.10.1
  get_it: ^7.6.7
  retrofit: ^4.4.1
  auto_route: ^7.8.4
  flutter_bloc: ^8.1.4
  alice: ^0.4.1
  provider: ^6.1.2
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  retrofit_generator: ^8.2.1
  build_runner: ^2.4.11
  auto_route_generator: ^7.3.2

flutter:
  uses-material-design: true
